_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: GCPGroupManager
  description: Manage groups in GCP.
  background_color: "#000000"
features:
  bot_user:
    display_name: GCPGroupManager
    always_online: false
oauth_config:
  scopes:
    bot:
      - app_mentions:read
      - chat:write
      - conversations.connect:manage
      - users.profile:read
      - users:read
      - users:read.email
settings:
  event_subscriptions:
    bot_events:
      - app_mention
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
